/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-07-09 07:19:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1751246541483L));
    _jspx_dependants.put("jar:file:/C:/Class/SpringClass/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SL07_UPLOAD2_AJAX/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<title>Home</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1>\n");
      out.write("	Hello world!  \n");
      out.write("</h1>\n");
      out.write("\n");
      out.write("<P>  The time on the server is ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serverTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(". </P>\n");
      out.write("\n");
      out.write("<h3>\n");
      out.write("	<a href=\"/time\">/time</a>\n");
      out.write("</h3>\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("\n");
      out.write("	1. <a href=\"/time\">/time</a> 요청\n");
      out.write("	2. org.doit.ik.mapper.TimeMapper 인터페이스\n");
      out.write("	3. 사용할 DB: ORM(mybatis)\n");
      out.write("		(1) pom.xml\n");
      out.write("			 - https://mvnrepository.com/artifact/org.mybatis/mybatis p91\n");
      out.write("			      <dependency>\n");
      out.write("			          <groupId>org.mybatis</groupId>\n");
      out.write("			          <artifactId>mybatis</artifactId>\n");
      out.write("			          <version>3.4.6</version>\n");
      out.write("			      </dependency>\n");
      out.write("		     - https://mvnrepository.com/artifact/org.mybatis/mybatis-spring\n");
      out.write("			      <dependency>\n");
      out.write("			          <groupId>org.mybatis</groupId>\n");
      out.write("			          <artifactId>mybatis-spring</artifactId>\n");
      out.write("			          <version>1.3.2</version>\n");
      out.write("			      </dependency>\n");
      out.write("\n");
      out.write("		(2) org.doit.ik.mapper 패키지 안에 mybatis-config.xml 생성\n");
      out.write("		\n");
      out.write("		(3) src/main/resources 폴더\n");
      out.write("			ㄴ org 폴더 생성\n");
      out.write("				ㄴ doit 폴더 생성\n");
      out.write("					ㄴ ik 폴더 생성\n");
      out.write("						ㄴ mapper 폴더 생성\n");
      out.write("							ㄴ TimeMapper.xml 추가 (인터페이스명(예: TimeMapper.java)과 동일하게 만들면 관리가 용이함)\n");
      out.write("								ㄴ 해당 Mapper 파일로 인해 Implementation이 가능해짐\n");
      out.write("		\n");
      out.write("		(4) log4jdbc.log4j2.properties 파일 추가, log4j.xml 파일 수정\n");
      out.write("		\n");
      out.write("		(5) root-context.xml 파일 수정\n");
      out.write("		\n");
      out.write("		(6) ojdbc6.jar 설정\n");
      out.write("	\n");
      out.write("	4. views 폴더\n");
      out.write("		ㄴ time.jsp 추가\n");
      out.write("	\n");
      out.write("	5. \n");
      out.write("-->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
